[I 200703 11:32:48 inrepo:35] Testing notebook notebooks/fig_8_frequency_change_vs_particle_separation.ipynb
[I 200703 11:32:49 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 76, in <module>
    main()
  File "/src/inrepo.py", line 72, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 38, in run_notebook
    exported = executenb(nb, cwd=os.path.dirname(nb_path))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax1, ax2 = create_figure_and_inset()

plot_frequency_change_vs_particle_distance(x=0, y=0, linestyle='-', ax=ax1, Nvals=[1, 2, 3, 4, 5], show_legend=True)
plot_frequency_change_vs_particle_distance(x=0, y=20, linestyle='-', ax=ax2, **kwargs_for_inset)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-7-a3e3ad1fcf2d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mfig[0m[0;34m,[0m [0max1[0m[0;34m,[0m [0max2[0m [0;34m=[0m [0mcreate_figure_and_inset[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mplot_frequency_change_vs_particle_distance[0m[0;34m([0m[0mx[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mlinestyle[0m[0;34m=[0m[0;34m'-'[0m[0;34m,[0m [0max[0m[0;34m=[0m[0max1[0m[0;34m,[0m [0mNvals[0m[0;34m=[0m[0;34m[[0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;36m4[0m[0;34m,[0m [0;36m5[0m[0;34m][0m[0;34m,[0m [0mshow_legend[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mplot_frequency_change_vs_particle_distance[0m[0;34m([0m[0mx[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;36m20[0m[0;34m,[0m [0mlinestyle[0m[0;34m=[0m[0;34m'-'[0m[0;34m,[0m [0max[0m[0;34m=[0m[0max2[0m[0;34m,[0m [0;34m**[0m[0mkwargs_for_inset[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-3-9d7d47e289d9>[0m in [0;36mcreate_figure_and_inset[0;34m()[0m
[1;32m     17[0m     [0max2[0m[0;34m.[0m[0mxaxis[0m[0;34m.[0m[0mset_ticks_position[0m[0;34m([0m[0;34m'bottom'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m     [0max2[0m[0;34m.[0m[0myaxis[0m[0;34m.[0m[0mset_ticks_position[0m[0;34m([0m[0;34m'left'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 19[0;31m     [0max2[0m[0;34m.[0m[0mset_axis_bgcolor[0m[0;34m([0m[0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0;34m[0m[0m
[1;32m     21[0m     [0;32mreturn[0m [0mfig[0m[0;34m,[0m [0max1[0m[0;34m,[0m [0max2[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'Axes' object has no attribute 'set_axis_bgcolor'
AttributeError: 'Axes' object has no attribute 'set_axis_bgcolor'


Container exited with status: {'Error': None, 'StatusCode': 1}
