[I 200710 13:23:29 inrepo:36] Testing notebook 010-Paramiko and hw1.ipynb
[I 200710 13:23:29 inrepo:45] Found kernel python3
[I 200710 13:23:30 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 114, in <module>
    main()
  File "/src/inrepo.py", line 110, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 75, in run_notebook
    nb, cwd=os.path.dirname(nb_path), kernel_name=kernel_name, timeout=600
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
client.connect(hostname='localhost',username='root',password='pwd',port=22022)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-4-f26bca2a0581>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mclient[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0mhostname[0m[0;34m=[0m[0;34m'localhost'[0m[0;34m,[0m[0musername[0m[0;34m=[0m[0;34m'root'[0m[0;34m,[0m[0mpassword[0m[0;34m=[0m[0;34m'pwd'[0m[0;34m,[0m[0mport[0m[0;34m=[0m[0;36m22022[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/paramiko/client.py[0m in [0;36mconnect[0;34m(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase, disabled_algorithms)[0m
[1;32m    347[0m                         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    348[0m                             [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 349[0;31m                     [0mretry_on_signal[0m[0;34m([0m[0;32mlambda[0m[0;34m:[0m [0msock[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0maddr[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    350[0m                     [0;31m# Break out of the loop on success[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    351[0m                     [0;32mbreak[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/paramiko/util.py[0m in [0;36mretry_on_signal[0;34m(function)[0m
[1;32m    281[0m     [0;32mwhile[0m [0;32mTrue[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    282[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 283[0;31m             [0;32mreturn[0m [0mfunction[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    284[0m         [0;32mexcept[0m [0mEnvironmentError[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    285[0m             [0;32mif[0m [0me[0m[0;34m.[0m[0merrno[0m [0;34m!=[0m [0merrno[0m[0;34m.[0m[0mEINTR[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/paramiko/client.py[0m in [0;36m<lambda>[0;34m()[0m
[1;32m    347[0m                         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    348[0m                             [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 349[0;31m                     [0mretry_on_signal[0m[0;34m([0m[0;32mlambda[0m[0;34m:[0m [0msock[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0maddr[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    350[0m                     [0;31m# Break out of the loop on success[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    351[0m                     [0;32mbreak[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: [Errno 99] Cannot assign requested address
OSError: [Errno 99] Cannot assign requested address


Container exited with status: {'Error': None, 'StatusCode': 1}
