[I 200707 12:36:04 inrepo:36] Testing notebook notebooks/submission.ipynb
[I 200707 12:36:05 inrepo:45] Found kernel python3
[I 200707 12:36:06 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 112, in <module>
    main()
  File "/src/inrepo.py", line 108, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 74, in run_notebook
    exported = executenb(nb, cwd=os.path.dirname(nb_path), kernel_name=kernel_name)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
txt = "governing law shall be defined as"
test_submission.predict([txt.split()])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-4-c1673f7efc48>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mtxt[0m [0;34m=[0m [0;34m"governing law shall be defined as"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mtest_submission[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0;34m[[0m[0mtxt[0m[0;34m.[0m[0msplit[0m[0;34m([0m[0;34m)[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/python/gorenml.py[0m in [0;36mpredict[0;34m(self, X, y)[0m
[1;32m     20[0m [0;34m[0m[0m
[1;32m     21[0m     [0;32mdef[0m [0mpredict[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mX[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 22[0;31m         [0mmodel[0m[0;34m,[0m [0mparams[0m [0;34m=[0m [0mload_model[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mmodel_folder[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m         [0;32mif[0m [0mtype[0m[0;34m([0m[0mX[0m[0;34m)[0m[0;34m==[0m[0mlist[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m             [0;32mreturn[0m [0;34m[[0m[0mpredict_on_token_array[0m[0;34m([0m[0mx[0m[0;34m,[0m [0mmodel[0m[0;34m,[0m [0mparams[0m[0;34m)[0m [0;32mfor[0m [0mx[0m [0;32min[0m [0mX[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/python/style_predict.py[0m in [0;36mload_model[0;34m(folder)[0m
[1;32m     11[0m [0;32mdef[0m [0mload_model[0m[0;34m([0m[0mfolder[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m     [0;34m"""Loads model files, and returns keras model and parameters"""[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfolder[0m [0;34m+[0m [0;34m'/model_architecture.json'[0m[0;34m,[0m [0;34m'r'[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m"utf-8"[0m[0;34m,[0m [0merrors[0m[0;34m=[0m[0;34m"ignore"[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m         [0mmodel[0m [0;34m=[0m [0mmodel_from_json[0m[0;34m([0m[0mf[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m     [0mmodel[0m[0;34m.[0m[0mload_weights[0m[0;34m([0m[0mfolder[0m [0;34m+[0m [0;34m'/model_weights.h5'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/vildeeide/model/model_architecture.json'
FileNotFoundError: [Errno 2] No such file or directory: '/home/vildeeide/model/model_architecture.json'


Container exited with status: {'Error': None, 'StatusCode': 1}
