[I 200707 07:17:46 inrepo:35] Testing notebook lab-11-0-cnn_basics.ipynb
[I 200707 07:17:47 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 76, in <module>
    main()
  File "/src/inrepo.py", line 72, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 38, in run_notebook
    exported = executenb(nb, cwd=os.path.dirname(nb_path))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
sess = tf.InteractiveSession()
image = np.array([[[[1],[2],[3]],
                   [[4],[5],[6]], 
                   [[7],[8],[9]]]], dtype=np.float32)
print(image.shape)
plt.imshow(image.reshape(3,3), cmap='Greys')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-faaf58d6b33d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0msess[0m [0;34m=[0m [0mtf[0m[0;34m.[0m[0mInteractiveSession[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m image = np.array([[[[1],[2],[3]],
[1;32m      3[0m                    [0;34m[[0m[0;34m[[0m[0;36m4[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;36m5[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;36m6[0m[0;34m][0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m                    [[7],[8],[9]]]], dtype=np.float32)
[1;32m      5[0m [0mprint[0m[0;34m([0m[0mimage[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'tensorflow' has no attribute 'InteractiveSession'
AttributeError: module 'tensorflow' has no attribute 'InteractiveSession'


Container exited with status: {'Error': None, 'StatusCode': 1}
