[I 200713 09:39:17 inrepo:36] Testing notebook notebooks/py-processors-intro.ipynb
[I 200713 09:39:18 inrepo:45] Found kernel python3
[I 200713 09:39:18 execute:404] Executing notebook with kernel: python3
[W 200713 09:40:44 execute:599] Timeout waiting for IOPub output
Traceback (most recent call last):
  File "/src/inrepo.py", line 114, in <module>
    main()
  File "/src/inrepo.py", line 110, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 75, in run_notebook
    nb, cwd=os.path.dirname(nb_path), kernel_name=kernel_name, timeout=600
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# How many sentences?
doc.size
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-3-ba11ad5ff270>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# How many sentences?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdoc[0m[0;34m.[0m[0msize[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'NoneType' object has no attribute 'size'
AttributeError: 'NoneType' object has no attribute 'size'


Container exited with status: {'Error': None, 'StatusCode': 1}
